name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag logicfocus/docker-image-autobuild:latest
    - name: push the Docker image
      run: docker login -u logicfocus -p ${{ secrets DOCKER_TOKEN }} && docker push logicfocus/docker-image-autobuild:latest  
