

       name: ci
 on:
    push:
      branches:
        - master
    jobs:
        
    build:

         - name: Checkout project
           uses: actions/checkout@v2

         - name: Build image
           run: |
              docker build -t test_image:latest -<<EOF
              FROM busybox
              RUN touch abc.txt
              EOF

         - name: Upload image
           uses: ishworkh/docker-image-artifact-upload@v1
           with:
                          image: "test_image:latest"





































